### ISSUE TITLE
Bug Report: doesn't draw to scale

### ISSUE THREAD

**Issue by flocu** [tamc/macc#1]
Nice MACC Tool. But it doesn't draw to scale, even with the sample data.

"Thing 3" should be 100 but is drawn as 20.

It's not even proportional. Try to enter 100 as value and they are all drawn differently.

**Comment by tamc** [comment]
The second column is the area, not the height.

e.g., in the example:

    Name	 Category	Abatement potential	 Cost
    Thing 3	Category 1	5	100

The last column is the cost, but if you look at the chart labels, the y axis is £/tCO2e, i.e., the cost per unit of abatement potential, which in this case = 100/5 = 20 which is how it is drawn.

**Comment by flocu** [comment]
Oh, now I see. Thanks for clarifying.

That's not how any of the abatement curves I've seen before are used, including the McKinsey curve, that sparked the whole craze.

Usually the axes are orthogonal - in every meaning of the word.

**Comment by flocu** [comment]
If anyone else runs into this problem, just change line 438 from
  return delta_y/Math.abs(delta_x);
to
  return delta_y;

@tamc Without your clarification, I wouldn't have been able to solve this for my use-case. Thanks again!

**Comment by tamc** [comment]
Yes, axes are orthogonal, but the data I got from the models when making this was not ;-)
